#!/usr/bin/env bash
HERE="$(dirname "$(readlink -f "${0}")")"
export APPDIR="$HERE"
cd "$HERE"
cd usr
HERE="$(pwd)"
export PATH="${PATH}:/sbin:/usr/sbin"
export LD_LIBRARY_PATH="$HERE/lib:/usr/lib:$LD_LIBRARY_PATH"
export XDG_DATA_DIRS="${HERE}/share/:${HERE}/share/mime/:${XDG_DATA_DIRS}"
export GTK_PATH="${HERE}/lib/gtk-2.0:${GTK_PATH}"
export PANGO_LIBDIR="${HERE}/lib"
export GCONV_PATH="${HERE}/lib/gconv"
export GDK_PIXBUF_MODULEDIR="${HERE}/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders"
export GDK_PIXBUF_MODULE_FILE="${HERE}/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache"

if [[ -e /etc/fonts/fonts.conf ]]; then
  export FONTCONFIG_PATH=/etc/fonts
fi

# libstdc++ version detection
stdcxxlib="$(ldconfig -p | grep 'libstdc++.so.6 (libc6,x86-64)'| awk 'NR==1{print $NF}')"
echo "System stdc++ library: \"$stdcxxlib\""
stdcxxver1="$(strings "$stdcxxlib" | grep '^GLIBCXX_[0-9].[0-9]*' | cut -d"_" -f 2 | sort -V | tail -n 1)"
echo "System stdc++ library version: \"$stdcxxver1\""
stdcxxver2="$(strings "$HERE/optional/libstdc++/libstdc++.so.6" | grep '^GLIBCXX_[0-9].[0-9]*' | cut -d"_" -f 2 | sort -V | tail -n 1)"
echo "Bundled stdc++ library version: \"$stdcxxver2\""
stdcxxnewest="$(echo "$stdcxxver1 $stdcxxver2" | tr " " "\n" | sort -V | tail -n 1)"
echo "Newest stdc++ library version: \"$stdcxxnewest\""
if [[ x"$stdcxxnewest" = x"$stdcxxver1" ]]; then
   echo "Using system stdc++ library"
else
   echo "Using bundled stdc++ library"
   export LD_LIBRARY_PATH="${HERE}/optional/libstdc++:${LD_LIBRARY_PATH}"
 fi

ldd "./bin/rawtherapee"
"./bin/rawtherapee.wrapper" "$@"
